<?php
// Path: src/modules/admin/control/add-control.php
require_once '../../../config/config.php';
requireRole(['admin']);

$db = new Database();

// Fetch Sections
$sections = $db->fetchAll("SELECT sec_ID, sec_name FROM section WHERE type = 'Control' ORDER BY sec_ID ASC");

// Handle Form Submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        // REMOVED: $sub_con_id = sanitize($_POST['sub_con_id']);
        $sub_con_name = sanitize($_POST['sub_con_name']);
        $sec_id = sanitize($_POST['sec_id']);

        if (empty($sub_con_name) || empty($sec_id)) {
            throw new Exception('All fields are required.');
        }

        // Insert WITHOUT sub_con_id (The Trigger will handle it)
        // We pass NULL or skip the column so the trigger sets it
        $sql = "INSERT INTO sub_con (sub_con_name, sec_ID) VALUES (:name, :sec)";
        $db->query($sql, [
            ':name' => $sub_con_name,
            ':sec' => $sec_id
        ]);

        // Get the ID that was just generated (Optional: purely for success message)
        // Since it's a string key generated by trigger, we can't use lastInsertId().
        // We can just say "Control added successfully".
        
        setFlashMessage('success', "New Control added successfully.");
        header('Location: index.php');
        exit();

    } catch (Exception $e) {
        setFlashMessage('danger', $e->getMessage());
    }
}

$flash = getFlashMessage();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add ISO Control - <?php echo APP_NAME; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <style>
        html, body { height: 100%; margin: 0; padding: 0; overflow-x: hidden; background-color: #f8f9fa; }
        .main-content-wrapper { margin-left: 270px; width: calc(100% - 270px); }
        body.sb-collapsed .main-content-wrapper { margin-left: 80px; width: calc(100% - 80px); }
        @media (max-width: 991.98px) { .main-content-wrapper { margin-left: 0; width: 100%; } }
        .card { border: none; border-radius: 16px; box-shadow: 0 4px 6px rgba(50, 50, 93, 0.11); }
        .btn-gradient-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border: none; color: white;
        }
        .btn-gradient-primary:hover { opacity: 0.9; color: white; }
    </style>
</head>
<body>
    <div class="container-fluid p-0 h-100">
        <div class="row g-0 h-100">
            <div class="col-auto">
                <?php include_once __DIR__ . '/../../includes/admin_sidebar.php'; ?>
            </div>
            <div class="col main-content-wrapper">
                <div class="main-content px-4 py-4">

                    <nav aria-label="breadcrumb" class="mb-4">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="../dashboard.php" class="text-decoration-none text-secondary">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="../parameter-settings.php" class="text-decoration-none text-secondary">Parameter Settings</a></li>
                            <li class="breadcrumb-item"><a href="index.php" class="text-decoration-none text-secondary">ISO Controls</a></li>
                            <li class="breadcrumb-item active text-dark">Add Control</li>
                        </ol>
                    </nav>

                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="card">
                                <div class="card-header bg-white border-bottom py-3 rounded-top-4">
                                    <h5 class="mb-0">Add New Control</h5>
                                </div>
                                <div class="card-body p-4">
                                    
                                    <?php if ($flash): ?>
                                        <div class="alert alert-<?php echo $flash['type']; ?>"><?php echo $flash['message']; ?></div>
                                    <?php endif; ?>

                                    <form method="POST">
                                        <div class="mb-4">
                                            <label for="sec_id" class="form-label fw-bold">ISO Section <span class="text-danger">*</span></label>
                                            <select class="form-select" id="sec_id" name="sec_id" required>
                                                <option value="">-- Select Section --</option>
                                                <?php foreach ($sections as $sec): ?>
                                                    <option value="<?php echo htmlspecialchars($sec['sec_ID']); ?>">
                                                        <?php echo htmlspecialchars($sec['sec_ID'] . ' - ' . $sec['sec_name']); ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                            <div class="form-text">The Control ID (e.g., A.5.X) will be generated automatically based on this selection.</div>
                                        </div>

                                        <div class="mb-4">
                                            <label for="sub_con_name" class="form-label fw-bold">Control Name / Description <span class="text-danger">*</span></label>
                                            
                                            <textarea class="form-control" id="sub_con_name" name="sub_con_name" rows="3" maxlength="100"
                                                    placeholder="e.g. Information security roles and responsibilities" required></textarea>
                                                    
                                            <div class="d-flex justify-content-end mt-1">
                                                <small class="text-muted char-count" data-for="sub_con_name">100 characters remaining</small>
                                            </div>
                                        </div>

                                        <div class="d-flex justify-content-end gap-2 pt-3 border-top">
                                            <a href="index.php" class="btn btn-light px-4 rounded-3">Cancel</a>
                                            <button type="submit" class="btn btn-gradient-primary px-4 rounded-3 shadow-sm">
                                                <i class="bi bi-save me-2"></i>Save Control
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const counters = document.querySelectorAll('.char-count');
            counters.forEach(counter => {
                const input = document.getElementById(counter.getAttribute('data-for'));
                if (input) {
                    const updateCount = () => {
                        const remaining = input.getAttribute('maxlength') - input.value.length;
                        counter.textContent = `${remaining} characters remaining`;
                    };
                    updateCount();
                    input.addEventListener('input', updateCount);
                }
            });
        });
    </script>
</body>
</html>